language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<2.0"
  - DJANGO="Django>=2.0,<3.0"
  - DJANGO="Django>=3.0,<4.0"

matrix:
  include:
    # Run Python 2.6 on trusty
    - python: "2.6"
      env: DJANGO="Django>=1.4,<1.5"
      dist: trusty
    - python: "2.6"
      env: DJANGO="Django>=1.5,<1.6"
      dist: trusty
    - python: "2.6"
      env: DJANGO="Django>=1.6,<1.7"
      dist: trusty
    # Run Python 3.3 on trusty
    - python: "3.3"
      env: DJANGO="Django>=1.5,<1.6"
      dist: trusty
    - python: "3.3"
      env: DJANGO="Django>=1.6,<1.7"
      dist: trusty
    - python: "3.3"
      env: DJANGO="Django>=1.7,<1.8"
      dist: trusty
    - python: "3.3"
      env: DJANGO="Django>=1.8,<1.9"
      dist: trusty
  exclude:
    - python: "2.7"
      env: DJANGO="Django>=2.0,<3.0"
    - python: "2.7"
      env: DJANGO="Django>=3.0,<4.0"
    - python: "3.4"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.4"
      env: DJANGO="Django>=3.0,<4.0"
    - python: "3.5"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.5"
      env: DJANGO="Django>=1.5,<1.6"
    - python: "3.5"
      env: DJANGO="Django>=1.6,<1.7"
    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8"
    - python: "3.5"
      env: DJANGO="Django>=3.0,<4.0"
    - python: "3.6"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.6"
      env: DJANGO="Django>=1.5,<1.6"
    - python: "3.6"
      env: DJANGO="Django>=1.6,<1.7"
    - python: "3.6"
      env: DJANGO="Django>=1.7,<1.8"
    - python: "3.7"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.7"
      env: DJANGO="Django>=1.5,<1.6"
    - python: "3.7"
      env: DJANGO="Django>=1.6,<1.7"
    - python: "3.7"
      env: DJANGO="Django>=1.7,<1.8"
before_install:
  - PWD=`pwd`
  - echo '## Installing wkhtmltopdf dependencies'
  - sudo apt-get update -qq
  - sudo apt-get install -y libxrender1 libfontconfig1 zlib1g libfreetype6 libx11-6 libxext6
  - echo '## Installing wkhtmltopdf'
  - wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - export WKHTMLTOPDF_CMD="$PWD/wkhtmltox/bin/wkhtmltopdf"
install:
  - pip install $DJANGO
  - pip install -r test_requirements.txt
  - pip install .
script:
  - make test
notifications:
  email: false
